# ---------------------------------
# TEMPLATE DE COMPILAÇÃO AUTOMATICA
# ---------------------------------

name: Java Automatic Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Diretório onde vai ser feito o job
    #defaults:
    #  run:
    #    working-directory: src

    steps:
    - uses: actions/checkout@v2
    - name: Configurando o Java 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Instalando Modificações no POM.xml
      run: mvn clean install -B
    - name: Compilando o Projeto
      run: mvn compile -B
    - name: Rodar o Projeto entregando resultado
      run: mvn exec:java -B
